apiVersion: v1
kind: Service
metadata:
  name: helloworld-spring-boot-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: helloworld-spring-boot-app
