replicaCount: 2

image:
  repository: helloworld-spring-boot-app
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  image: postgres:15.2
  user: myuser
  password: secret
  database: mydatabase

springboot:
  livenessProbe:
    path: "/actuator/health/liveness"
    initialDelaySeconds: 10
    periodSeconds: 5
  readinessProbe:
    path: "/actuator/health/readiness"
    initialDelaySeconds: 10
    periodSeconds: 5